<?php

$region_taxonomy_labels = array(
		'name'                       => _x( 'Regions', 'Taxonomy General Name', 'region' ),
		'singular_name'              => _x( 'Region', 'Taxonomy Singular Name', 'region' ),
		'menu_name'                  => __( 'Region', 'region' ),
		'all_items'                  => __( 'All Items', 'region' ),
		'parent_item'                => __( 'Parent Item', 'region' ),
		'parent_item_colon'          => __( 'Parent Item:', 'region' ),
		'new_item_name'              => __( 'New Item Name', 'region' ),
		'add_new_item'               => __( 'Add New Item', 'region' ),
		'edit_item'                  => __( 'Edit Item', 'region' ),
		'update_item'                => __( 'Update Item', 'region' ),
		'view_item'                  => __( 'View Item', 'region' ),
		'separate_items_with_commas' => __( 'Separate items with commas', 'region' ),
		'add_or_remove_items'        => __( 'Add or remove items', 'region' ),
		'choose_from_most_used'      => __( 'Choose from the most used', 'region' ),
		'popular_items'              => __( 'Popular Items', 'region' ),
		'search_items'               => __( 'Search Items', 'region' ),
		'not_found'                  => __( 'Not Found', 'region' ),
		'no_terms'                   => __( 'No items', 'region' ),
		'items_list'                 => __( 'Items list', 'region' ),
		'items_list_navigation'      => __( 'Items list navigation', 'region' ),
	);

$region_post_labels = array(
		'name'                  => _x( 'Buildings', 'Post Type General Name', 'building' ),
		'singular_name'         => _x( 'Building', 'Post Type Singular Name', 'building' ),
		'menu_name'             => __( 'Buildings', 'building' ),
		'name_admin_bar'        => __( 'Building', 'building' ),
		'archives'              => __( 'Item Archives', 'building' ),
		'attributes'            => __( 'Item Attributes', 'building' ),
		'parent_item_colon'     => __( 'Parent Item:', 'building' ),
		'all_items'             => __( 'All Items', 'building' ),
		'add_new_item'          => __( 'Add New Item', 'building' ),
		'add_new'               => __( 'Add New', 'building' ),
		'new_item'              => __( 'New Item', 'building' ),
		'edit_item'             => __( 'Edit Item', 'building' ),
		'update_item'           => __( 'Update Item', 'building' ),
		'view_item'             => __( 'View Item', 'building' ),
		'view_items'            => __( 'View Items', 'building' ),
		'search_items'          => __( 'Search Item', 'building' ),
		'not_found'             => __( 'Not found', 'building' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'building' ),
		'featured_image'        => __( 'Featured Image', 'building' ),
		'set_featured_image'    => __( 'Set featured image', 'building' ),
		'remove_featured_image' => __( 'Remove featured image', 'building' ),
		'use_featured_image'    => __( 'Use as featured image', 'building' ),
		'insert_into_item'      => __( 'Insert into item', 'building' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'building' ),
		'items_list'            => __( 'Items list', 'building' ),
		'items_list_navigation' => __( 'Items list navigation', 'building' ),
		'filter_items_list'     => __( 'Filter items list', 'building' ),
	);
?>